adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.adminview, name='view'),
    path('users/', adminapp.UsersView.as_view(), name='users'),
    path('users/<int:page>', adminapp.UsersView.as_view(), name='users'),
    path('users/personal/<int:pk>', adminapp.UsersPersonal.as_view(), name='users-personal'),
    path('users/create', adminapp.UsersCreate.as_view(), name='users-create'),
    path('users/edit/<int:pk>', adminapp.UsersEdit.as_view(), name='users-edit'),
    path('users/delete/<int:pk>', adminapp.UsersDelete.as_view(), name='users-delete'),

    path('products/', adminapp.ProdcutsView.as_view(), name='products'),
    path('products/<int:page>', adminapp.ProdcutsView.as_view(), name='products'),
    path('products/personal/<int:pk>', adminapp.ProductsPersonal.as_view(), name='products-personal'),
    path('products/create', adminapp.ProductsCreate.as_view(), name='products-create'),
    path('products/edit/<int:pk>', adminapp.ProductsEdit.as_view(), name='products-edit'),
    path('products/delete/<int:pk>', adminapp.ProductsDelete.as_view(), name='products-delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('users.urls', namespace='users')),
    path('products/', include('products.urls', namespace='products')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
    path('', include('social_django.urls', namespace='social')),
]

handler404 = 'mainapp.views.not_found'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegistrView, EditView, verify
from .forms import UserLoginForm

app_name = 'users'

urlpatterns = [
    path('login', LoginView.as_view(template_name='users/login.html', authentication_form=UserLoginForm), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('registr', RegistrView, name='registr'), 
    path('edit', EditView, name='edit'),
    path('verify/<email>/<activation_key>/', verify, name='verify'),
]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import user_passes_test
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from users.forms import UserRegistrForm, UserEditForm
from products.forms import ProductCreateForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from products.models import Product

title = 'Admin'

@user_passes_test(lambda u: u.is_staff)
def adminview(request):
    return render(request, 'adminapp/base.html', {'title': title})

class UsersView(ListView):
    model = User
    template_name = 'adminapp/list.html'
    context_object_name = 'users_detail'
    paginate_by = 2

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

class UsersPersonal(DetailView):
    model = User
    template_name = 'adminapp/detail.html'
    context_object_name = 'user_detail'
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
class UsersCreate(CreateView):
    model = User
    template_name = 'adminapp/create.html'
    context_object_name = 'form'
    success_url = reverse_lazy('adminapp:users')
    form_class = UserRegistrForm
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
class UsersEdit(UpdateView):
    model = User
    template_name = 'adminapp/edit.html'
    success_url = reverse_lazy('adminapp:users')
    context_object_name = 'form'
    form_class = UserEditForm
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

class UsersDelete(DeleteView):
    model = User
    template_name = 'adminapp/delete.html'
    success_url = reverse_lazy('adminapp:users')
    context_object_name = "user_detail"
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
        
class ProdcutsView(ListView):
    model = Product
    template_name = 'adminapp/list.html'
    context_object_name = 'products'
    paginate_by = 2
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

class ProductsPersonal(DetailView):
    model = Product
    template_name = 'adminapp/detail.html'
    context_object_name = 'product_detail'
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
        
class ProductsCreate(CreateView):
    model = Product
    template_name = 'adminapp/create.html'
    success_url = reverse_lazy('adminapp:products')
    form_class = ProductCreateForm
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
        
class ProductsEdit(UpdateView):
    model = Product
    template_name = 'adminapp/edit.html'
    success_url = reverse_lazy('adminapp:products')
    form_class = ProductCreateForm
    context_object_name = 'form'
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

class ProductsDelete(DeleteView):
    model = Product
    template_name = 'adminapp/delete.html'
    success_url = reverse_lazy('adminapp:products')
    context_object_name = 'product'
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

adminapp/templates/adminapp/includes/inc_adminapp_header.html
<div class="menu">
    <ul class="munu__list">
        <li><a href="{% url 'adminapp:users' %}" >Users</a></li>
        <li><a href="{% url 'adminapp:products' %}" >Products</a></li>
    </ul>
</div>

adminapp/templates/adminapp/includes/inc_product.html
<div class="user__block">
    <div class="categorys">
        Name:<br>
        Category:<br>
        Price:<br>
        Image:<br>
    </div>
    <div class="data">
        {{ product_detail.name }}<br>
        {{ product_detail.category }}<br>
        {{ product_detail.price }}<br>
        <img src="{{ product_detail.image.url }}" alt="" style="width: 200px; height: 100px;"/>
    </div>
</div>

adminapp/templates/adminapp/includes/inc_products.html
<div class="users__block">
    {% for product in page_obj %}
        <span><a href="{% url 'adminapp:products-personal' product.id %}">Product {{ product.name|title }}</a></span>
        <button class="edit_button"><a href="{% url 'adminapp:products-edit' product.id %}">Edit</a></button>
        <button class="edit_button"><a href="{% url 'adminapp:products-delete' product.id %}">Delete</a></button><br>
    {% endfor %}
    <button><a href="{% url 'adminapp:products-create' %}">Create</a></button>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="{% url 'adminapp:products' page_obj.previous_page_number %}">&laquo;</a>
            {% endif %}
            <span class="current">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>
            {% if page_obj.has_next %}
                <a href="{% url 'adminapp:products' page_obj.next_page_number %}">&raquo;</a>
            {% endif %}
        </span>
    </div>
</div>

adminapp/templates/adminapp/includes/inc_user.html
<div class="user__block">
    <div class="categorys">
        Name:<br>
        Age:<br>
        Avatar:<br>
        Is active:<br>
    </div>
    <div class="data">
        {{ user_detail.get_full_name }}<br>
        {{ user_detail.profile.age }} y.o<br>
        <img src="{{ user_detail.profile.avatar.url }}" alt="" style="width: 200px; height: 100px;"/><br>
        {{ user_detail.is_active}}<br>
    </div>
</div>

adminapp/templates/adminapp/includes/inc_users.html
<div class="users__block">
    {% for user in page_obj %}
        <span><a href="{% url 'adminapp:users-personal' user.id %}">User {{ user.username|title }}</a></span>
        <button class="edit_button"><a href="{% url 'adminapp:users-edit' user.id %}">Edit</a></button>
        <button class="edit_button"><a href="{% url 'adminapp:users-delete' user.id %}">Delete</a></button><br>
    {% endfor %}
    <button><a href="{% url 'adminapp:users-create' %}">Create</a></button>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="{% url 'adminapp:users' page_obj.previous_page_number %}">&laquo;</a>
            {% endif %}
            <span class="current">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>
            {% if page_obj.has_next %}
                <a href="{% url 'adminapp:users' page_obj.next_page_number %}">&raquo;</a>
            {% endif %}
        </span>
    </div>
</div>