config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('users.urls', namespace='users')),
    path('products/', include('products.urls', namespace='products')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
    path('', include('social_django.urls', namespace='social')),
]

handler404 = 'mainapp.views.not_found'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from .views import indexView, contactView

app_name = 'mainapp'

urlpatterns = [
    path('', indexView, name='index'),
    path('contact', contactView, name='contact'),
]

ordersapp/urls.py
from django.urls import path
import ordersapp.views as views
from ordersapp.views import ProdctsAjaxHandler

app_name = 'orders'

urlpatterns = [
    path('', views.OrderListView.as_view(), name='list'),
    path('create/', views.OrderCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.OrderUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.OrderDeleteView.as_view(), name='delete'),
    path('read/<int:pk>', views.OrderRead.as_view(), name='read'),
    path('forming_complete/<int:pk>/', views.order_forming_complete, name='forming_complete'),
    path('products_get', ProdctsAjaxHandler, name='products_ajax')
]

products/urls.py
from django.urls import path
from .views import ProductsView, productPersonal

app_name = 'products'

urlpatterns = [
    path('<str:category>/', ProductsView.as_view(), name='category'),
    path('<str:category>/<int:page>', ProductsView.as_view(), name='page'),
    path('<str:category>/personal/<int:pk>', productPersonal, name='personal'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegistrView, EditView, verify
from .forms import UserLoginForm

app_name = 'users'

urlpatterns = [
    path('login', LoginView.as_view(template_name='users/login.html', authentication_form=UserLoginForm), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('registr', RegistrView, name='registr'), 
    path('edit', EditView, name='edit'),
    path('verify/<email>/<activation_key>/', verify, name='verify'),
]

mainapp/views.py
from basket.models import Basket
from django.shortcuts import render

def indexView(request):
    return render(request, 'mainapp/index.html', {'title': 'Магазин'})

def contactView(request):
    return render(request, 'mainapp/contact.html', {'title': 'Контакты'})

def not_found(request, exception):
    return render(request, 'mainapp/404.html', status=404)

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% if title %} {{ title }}
        {% else %} Document {% endif %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    {% block css %}
    {% endblock %}
    {% block js %}
    {% endblock %}
	<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
</head>
<body>

	<div class="container">
        {% block menu %}
        {% endblock %}

        {% block content %}
        {% endblock %}
	</div>
    {% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB {% now "Y" %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
    {% endblock %}
	
</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %} {% load static %}
		{% block menu %}
		<div class="hero">
			<div class="header clearfix">
				<a href="{% url 'mainapp:index' %}" class="logo"></a>
				{% include 'mainapp/includes/inc_main_menu.html' %}
				<a href="#" class="search"></a>
                <a href="{% url 'basket:index' %}" class="basket"></a>
			</div>
			<h1>наши контакты</h1>
		</div>
		{% endblock %}
		{% block content %}
		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>
		{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %} {% load static %}
		{% block menu %}
		<div class="slider">
			<div class="header clearfix">
				<a href="{% url 'mainapp:index' %}" class="logo"></a>
				<ul class="menu">
					<li><a href="{% url 'mainapp:index' %}" class="active">домой</a></li>
					<li><a href="{% url 'products:category' 'all' %}">продукты</a></li>
					<li><a href="{% url 'mainapp:contact' %}">контакты</a></li>
					{% if user.is_authenticated %}
        				<a href="{% url 'users:edit' %}">{{ user.username }}</a> | <a href="{% url 'users:logout' %}">logout</a>
						<a href="{% url 'ordersapp:list' %}">orders</a>
					{% else %}
						<a href="{% url 'users:login' %}">login</a>
						<a href="{% url 'users:registr' %}">registration</a>
					{% endif %}
					{% if user.is_superuser %}
					<a href="{% url 'adminapp:users' %}">admin</a>
					{% endif %}
				</ul>
				<a href="#" class="search"></a>
				<a href="{% url 'basket:index' %}" class="basket">
					<div style="position: relative; left: 30px;">{% if basket %}{{ basket.total_quantity }}, {{ basket.total_cost }}{% endif %}</div>
				</a>
			</div>
			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
			</div>	
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>
		{% endblock %}
		{% block content %}
		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				<div class="block">
					<a href="#"><img src="{% static 'img/product-1.jpg' %}" alt=""> 
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="img">
							<h4>Отличный стул</h4>
							<p>Расположитесь комфортно. </p>
						</div> 
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static 'img/product-2.jpg' %}" alt="">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>	
			</div>
		</div>

		<div class="clr"></div>
		{% endblock %}
</body>
</html>