basket/urls.py
from django.urls import path
from .views import basket, basketAdd, basketDelete
app_name = 'basket'

urlpatterns = [
    path('', basket, name='index'),
    path('add/<int:pk>', basketAdd, name='add'),
    path('delete/<int:pk>', basketDelete, name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('users.urls', namespace='users')),
    path('products/', include('products.urls', namespace='products')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
    path('', include('social_django.urls', namespace='social')),
]

handler404 = 'mainapp.views.not_found'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import ProductsView, productPersonal

app_name = 'products'

urlpatterns = [
    path('<str:category>/', ProductsView.as_view(), name='category'),
    path('<str:category>/<int:page>', ProductsView.as_view(), name='page'),
    path('<str:category>/personal/<int:pk>', productPersonal, name='personal'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegistrView, EditView, verify
from .forms import UserLoginForm

app_name = 'users'

urlpatterns = [
    path('login', LoginView.as_view(template_name='users/login.html', authentication_form=UserLoginForm), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('registr', RegistrView, name='registr'), 
    path('edit', EditView, name='edit'),
    path('verify/<email>/<activation_key>/', verify, name='verify'),
]

products/models.py
from django.db import models

class Product_category(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=20)
    quantity = models.PositiveSmallIntegerField(default=100)
    image = models.ImageField(upload_to='product_images', blank=True)
    price = models.IntegerField(default=100)
    category = models.ForeignKey(Product_category, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

products/forms.py
from django.forms import ModelForm
from .models import Product

class ProductCreateForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

products/views.py
from django.shortcuts import get_object_or_404, render, get_list_or_404
from django.views.generic.list import ListView
from basket.models import Basket
from .models import Product, Product_category

class ProductsView(ListView):
    template_name = 'products/products.html'
    context_object_name = 'products'
    paginate_by = 2
    
    def get_queryset(self):
        if self.kwargs['category'] != "all":
            return get_list_or_404(Product, category__pk=Product_category.objects.get(name=self.kwargs['category']).id)
        else:
            return get_list_or_404(Product)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Продукты'
        context["categorys"] = Product_category.objects.all()
        context["active"] = self.kwargs['category']
        return context

def productPersonal(request, category, pk):
    product = get_object_or_404(Product, id=pk)
    return render(request, 'products/personal.html', {'title': 'Продукты','product': product})

products/templates/products/personal.html
{% extends 'mainapp/base.html' %} {% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'personal.css' %}">
{% endblock %}
{% block menu %}
<div class="hero-white">
    <div class="header clearfix">
        <a href="{% url 'mainapp:index' %}" class="logo"></a>
        {% include 'mainapp/includes/inc_main_menu.html' %}
        <a href="#" class="search"></a>
        <a href="#" class="basket"></a>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="product__block">
    <div class="product">
        <img src="{{ product.image.url }}" style="width: 300px;"/>
        <a href="{% url 'basket:add' product.id %}" class="product__order">Заказать</a>
    </div>
</div>
{% endblock %}

products/templates/products/products.html
{% extends 'mainapp/base.html' %} {% load static %}
		{% block menu %}
		<div class="hero-white">
			<div class="header clearfix">
				<a href="{% url 'mainapp:index' %}" class="logo"></a>
				{% include 'mainapp/includes/inc_main_menu.html' %}
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
			</div>
		</div>
		{% endblock %}
		{% block content %}
		<div class="details">
			<div class="links clearfix">
				<ul class="links-menu">
					{% for category in categorys %}
					<li><a href="{% url 'products:category' category.name %}" {% if active == category.name %} class="active" {% endif %}>{{category.name}}</a></li>
					{% endfor %}
				</ul>
			</div>
			<div class="pagination">
				<span class="step-links">
					{% if page_obj.has_previous %}
						<a href="{% url 'products:page' active page_obj.previous_page_number %}">&laquo;</a>
					{% endif %}
					<span class="current">
						{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
					</span>
					{% if page_obj.has_next %}
						<a href="{% url 'products:page' active page_obj.next_page_number %}">&raquo;</a>
					{% endif %}
				</span>
			</div>
			<div class="products">
				<div class="related-products clearfix">
					{% for product in page_obj %}
						<div class="block made_my">
							<a href="{% url 'products:personal' product.category.name product.id %}">
								<img src="{{ product.image.url }}" alt="" class="prod_img" style="width: 370px"/>
								<div class="text">
									<img src="{% static 'img/icon-hover.png' %}" alt="img">
									<h4>{{ product.name }}</h4>
								</div>
							</a>
						</div>
					{% endfor %}
				</div>
			</div>
			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="{% static 'img/slider1.jpg' %}">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">Отличный стул</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> 2585.9 <span>руб</span></p>
					<a href="#" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						<p>Расположитесь комфортно.</p> 
						<p>Отличное качество материалов
						позволит вам это.</p> 
						<p>Различные цвета</p>
						<p>высочайший уровень
						эргономики и прочность.</p>
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="{% static 'img/product-11.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'img/product-21.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'img/product-31.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>

				</div>
			</div>
		</div>
		{% endblock %}